
name: build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up job
        run: echo "Starting"

      - name: Checkout
        uses: actions/checkout@v2

      - name: Checkout builds
        uses: actions/checkout@v2
        with:
          ref: builds
          path: builds

      # [FIXED v1] The -f flag is added to prevent an error if no files are found
      - name: Clean old builds
        run: rm -f $GITHUB_WORKSPACE/builds/*.cs3

      - name: Setup JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Build Plugins
        run: |
          ./gradlew :plugins:ExampleProvider:assembleRelease
          # ./gradlew :plugins:ArabicProvider:assembleRelease # Example
          mv plugins/ExampleProvider/build/outputs/apk/release/*.cs3 builds/

      - name: Push builds
        run: |
          cd builds
          git config --global user.name "adamwolker21"
          git config --global user.email "adamwolker21@users.noreply.github.com"
          git add .
          git commit -m "Update builds" || exit 0
          git push
      - name: Post Checkout builds
        run: echo "idk"

      - name: Post Checkout
        run: echo "idk"

      - name: Complete job
        run: echo "Done"
