name: Build Plugins
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout builds
        uses: actions/checkout@v4
        with:
          ref: builds
          path: builds

      - name: Clean old builds
        run: rm -f builds/*.cs3

      - name: Sanitize builds checkout
        run: |
          if [ -f "builds/build.gradle.kts" ]; then
            mv builds/build.gradle.kts builds/build.gradle.kts.bak
          fi

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Build Plugins
        run: ./gradlew assembleRelease

      - name: Push builds
        run: |
          # The two lines below are the fix. They configure git with a user identity.
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          cd builds
          # Use find to locate the .cs3 file regardless of its subdirectory
          find ../ -name "*.cs3" -exec mv {} . \;
          # Remove the temporary backup file if it exists
          rm -f build.gradle.kts.bak
          git add .
          git commit -m "Update builds" || true
          git push origin builds

      - name: Post Checkout builds
        run: "true"

      - name: Post Checkout
        run: "true"

      - name: Complete job
        run: "true"
