# v2: Corrected the build path to target the Asia2tv plugin instead of the example.
name: Build

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout builds
        uses: actions/checkout@v4
        with:
          ref: builds
          path: builds

      - name: Clean old builds
        run: rm -f builds/*.cs3

      - name: Sanitize builds checkout
        run: |
          if [[ -f "builds/build.gradle.kts" ]]; then
            mv builds/build.gradle.kts builds/build.gradle.kts.bak
          fi

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Build Plugins
        run: |
          chmod +x ./gradlew
          # التغيير الأول هنا: استبدال ExampleProvider بـ Asia2tv
          ./gradlew :plugins:Asia2tv:assembleRelease --stacktrace

      - name: Push builds
        run: |
          cd builds
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git rm -f --ignore-unmatch *.cs3
          # التغيير الثاني هنا: البحث عن ملف .cs3 في مجلد Asia2tv
          find ../plugins/Asia2tv/build -type f -name "*.cs3" -exec mv {} . \;
          # Verify that the file was moved
          ls -l
          if [[ -z $(git status -s) ]]; then
            echo "No changes to commit"
            exit 0
          fi
          git add .
          git commit -m "Update plugins"
          git push
