# v3.1: Dynamic build process that automatically finds and builds all plugins.
name: Build

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout builds
        uses: actions/checkout@v4
        with:
          ref: builds
          path: builds

      - name: Clean old builds
        run: rm -f builds/*.cs3

      - name: Sanitize builds checkout
        run: |
          if [[ -f "builds/build.gradle.kts" ]]; then
            mv builds/build.gradle.kts builds/build.gradle.kts.bak
          fi

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Build All Plugins
        run: |
          chmod +x ./gradlew
          # هذا الجزء يبحث عن كل مجلد داخل "plugins" ويقوم ببنائه
          for D in ./plugins/*; do
            if [ -d "${D}" ]; then
              PLUGIN_NAME=$(basename -- "${D}")
              echo "Building plugin: ${PLUGIN_NAME}"
              ./gradlew ":plugins:${PLUGIN_NAME}:assembleRelease" --stacktrace
            fi
          done

      - name: Build Plugins
        run: |
          cd $GITHUB_WORKSPACE/src
          chmod +x gradlew
          ./gradlew make makePluginsJson
          ./gradlew ensureJarCompatibility
          cp **/build/*.cs3 $GITHUB_WORKSPACE/builds
          cp build/plugins.json $GITHUB_WORKSPACE/builds

      - name: Push builds
        run: |
          cd $GITHUB_WORKSPACE/builds
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit --amend -m "Build $GITHUB_SHA" || exit 0   # do not error if nothing to commit
          git push --force
