# v3: Correct the Gradle build path and the 'mv' command path.
# The project structure is now properly defined in Gradle settings,
# so we can call the build task with the correct module path.

name: build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up job
        run: echo "Starting"

      - name: Checkout
        uses: actions/checkout@v2

      - name: Checkout builds
        uses: actions/checkout@v2
        with:
          ref: builds
          path: builds

      - name: Clean old builds
        run: rm -f $GITHUB_WORKSPACE/builds/*.cs3

      - name: Sanitize builds checkout
        run: |
          if [ -f "builds/build.gradle.kts" ]; then
            mv builds/build.gradle.kts builds/build.gradle.kts.bak
          fi

      - name: Setup JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Build Plugins
        run: |
          # [FIXED v3] Corrected the Gradle task path.
          # It should point directly to the module name defined in settings.gradle.kts.
          ./gradlew :ExampleProvider:assembleRelease
          
          # [FIXED v3] Corrected the path for the 'mv' command to find the built .cs3 file.
          mv ExampleProvider/build/outputs/apk/release/*.cs3 builds/

      - name: Push builds
        run: |
          cd builds
          git config --global user.name "adamwolker21"
          git config --global user.email "adamwolker21@users.noreply.github.com"
          rm -f build.gradle.kts.bak
          git add .
          git commit -m "Update builds" || exit 0
          git push
      - name: Post Checkout builds
        run: echo "idk"

      - name: Post Checkout
        run: echo "idk"

      - name: Complete job
        run: echo "Done"
